aftercode = ""

beforecode = raw_input("Enter text")
aftercode = []

for x in beforecode:
  x = x.replace('a',"11")
  x = x.replace('b',"12")
  x = x.replace('c',"13")
  x = x.replace('d',"14")
  x = x.replace('e',"15")
  x = x.replace('f',"21")
  x = x.replace('g',"22")
  x = x.replace('h',"23")
  x = x.replace('i',"24")
  x = x.replace('j',"25")
  x = x.replace('l',"31")
  x = x.replace('m',"32")
  x = x.replace('n',"33")
  x = x.replace('o',"34")
  x = x.replace('p',"35")
  x = x.replace('q',"41")
  x = x.replace('r',"42")
  x = x.replace('s',"43")
  x = x.replace('t',"44")
  x = x.replace('u',"45")
  x = x.replace('v',"51")
  x = x.replace('w',"52")
  x = x.replace('x',"53")
  x = x.replace('y',"54")
  x = x.replace('z',"55")
  x = x.replace('A',"11")
  x = x.replace('B',"12")
  x = x.replace('C',"13")
  x = x.replace('D',"14")
  x = x.replace('E',"15")
  x = x.replace('F',"21")
  x = x.replace('G',"22")
  x = x.replace('H',"23")
  x = x.replace('I',"24")
  x = x.replace('J',"25")
  x = x.replace('L',"31")
  x = x.replace('M',"32")
  x = x.replace('N',"33")
  x = x.replace('O',"34")
  x = x.replace('P',"35")
  x = x.replace('Q',"41")
  x = x.replace('R',"42")
  x = x.replace('S',"43")
  x = x.replace('T',"44")
  x = x.replace('U',"45")
  x = x.replace('V',"51")
  x = x.replace('W',"52")
  x = x.replace('X',"53")
  x = x.replace('Y',"54")
  x = x.replace('Z',"55")
  
  aftercode.append(x)
print (' '.join(aftercode))